-- File generated by the BNF Converter (bnfc 2.9.3).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Frontend.SkelInstant where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Frontend.AbsInstant

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Frontend.AbsInstant.Ident -> Result
transIdent x = case x of
  Frontend.AbsInstant.Ident string -> failure x

transProgram :: Frontend.AbsInstant.Program -> Result
transProgram x = case x of
  Frontend.AbsInstant.Prog stmts -> failure x

transStmt :: Frontend.AbsInstant.Stmt -> Result
transStmt x = case x of
  Frontend.AbsInstant.SAss ident exp -> failure x
  Frontend.AbsInstant.SExp exp -> failure x

transExp :: Frontend.AbsInstant.Exp -> Result
transExp x = case x of
  Frontend.AbsInstant.ExpAdd exp1 exp2 -> failure x
  Frontend.AbsInstant.ExpSub exp1 exp2 -> failure x
  Frontend.AbsInstant.ExpMul exp1 exp2 -> failure x
  Frontend.AbsInstant.ExpDiv exp1 exp2 -> failure x
  Frontend.AbsInstant.ExpLit integer -> failure x
  Frontend.AbsInstant.ExpVar ident -> failure x
