## File generated by the BNF Converter (bnfc 2.9.3).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : insc_jvm insc_llvm

# Rules for building the parser.

Frontend/AbsInstant.hs Frontend/LexInstant.x Frontend/ParInstant.y Frontend/PrintInstant.hs Frontend/TestInstant.hs : Instant.cf
	bnfc --haskell -p Frontend Instant.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Frontend/TestInstant : Frontend/AbsInstant.hs Frontend/LexInstant.hs Frontend/ParInstant.hs Frontend/PrintInstant.hs Frontend/TestInstant.hs
	${GHC} ${GHC_OPTS} $@

insc_jvm: Frontend/AbsInstant.hs Frontend/ParInstant.hs Frontend/LexInstant.hs Frontend/Frontend.hs src/JVM/*.hs src/JVM/*/*.hs src/shared/*.hs
	ghc -o insc_jvm src/JVM/JVM.hs

insc_llvm: Frontend/AbsInstant.hs Frontend/ParInstant.hs Frontend/LexInstant.hs Frontend/Frontend.hs src/LLVM/*.hs src/LLVM/*/*.hs src/shared/*/hs
	ghc -o insc_llvm src/LLVM/llvm.hs && llvm-as -o lib/runtime.bc lib/runtime.ll
# Rules for cleaning generated files.

clean :
	-find . -type f -name "*.hi" -exec rm -rf {} +
	-find . -type f -name "*.o" -exec rm -rf {} + 
	-find . -type f -name "*.log" -exec rm -rf {} + 
	-find . -type f -name "*.aux" -exec rm -rf {} + 
	-find . -type f -name "*.dvi" -exec rm -rf {} + 
	-find . -type f -name "*.j" -exec rm -rf {} +
	-find . -type f -name "*.class" -exec rm -rf {} +
	-find . -type f -name "*.bc" -exec rm -rf {} +
	-rm insc_jvm
	-rm insc_llvm


distclean : clean
	-rm -f Frontend/AbsInstant.hs Frontend/AbsInstant.hs.bak Frontend/ComposOp.hs Frontend/ComposOp.hs.bak Frontend/DocInstant.txt Frontend/DocInstant.txt.bak Frontend/ErrM.hs Frontend/ErrM.hs.bak Frontend/LayoutInstant.hs Frontend/LayoutInstant.hs.bak Frontend/LexInstant.x Frontend/LexInstant.x.bak Frontend/ParInstant.y Frontend/ParInstant.y.bak Frontend/PrintInstant.hs Frontend/PrintInstant.hs.bak Frontend/SkelInstant.hs Frontend/SkelInstant.hs.bak Frontend/TestInstant.hs Frontend/TestInstant.hs.bak Frontend/XMLInstant.hs Frontend/XMLInstant.hs.bak Frontend/ASTInstant.agda Frontend/ASTInstant.agda.bak Frontend/ParserInstant.agda Frontend/ParserInstant.agda.bak Frontend/IOLib.agda Frontend/IOLib.agda.bak Frontend/Main.agda Frontend/Main.agda.bak Frontend/Instant.dtd Frontend/Instant.dtd.bak Frontend/TestInstant Frontend/LexInstant.hs Frontend/ParInstant.hs Frontend/ParInstant.info Frontend/ParDataInstant.hs Makefile
	-rmdir -p Frontend/

# EOF
